### ISSUE TITLE
PINOUT questions

### ISSUE THREAD

**Issue by ikerexxe** [leonyuhanov/KS0108_RPI_Driver#2]
Hi,

I bought the [AZDelivery LCD Display](https://www.amazon.es/dp/B07DDKBCY7), a similar display to the one that you are using to develop this project, and I'm trying to make it work with a RaspPi4. It's also based on the KS0108 display, but this one has 2 chips instead of 3.

I'm having problems understanding the PINOUT that you reference. From the `README` file:
- SPI CS pin = GPIO-7
- SPI MOSI Pin = GPIO-10
- SPI CLK Pin = GPIO-11
- PIN_DI = GPIO-14
- PIN_RW = GPIO-15
- PIN_E = GPIO-18
- PIN_CS1 = GPIO-23
- PIN_CS2 = GPIO-24
- PIN_RES = GPIO-1

But if I take a look at `KS0108X3_RPI_Driver.h` I can see:
- uint8_t PIN_DI;
- uint8_t PIN_RW;
- uint8_t PIN_E;
- uint8_t PIN_CS1;
- uint8_t PIN_CS2;
- uint8_t PIN_RES;
- uint8_t SPI_CS_PIN=7;

So, the first question that comes to my mind is, is this project functional? If so, why are the `SPI MOSI Pin` and `SPI CLK Pin` missing from the `.h` file? Aren't they needed?

**Comment by leonyuhanov** [comment]
Heya
Yes this project is 100% functional here is a demo https://www.instagram.com/reel/C7OhyszPqaz/ 
SPI pins are predefined in the BCM library. They are Pin 19(GPIO10 MOSI) for DATA, Pin 23(GPIO11 SCLK) For clock & pin.

FYI if your screen has 2 chips IT MAY need to be driven differently. The screen I have has an addressable scheme for choosing what chip is active for data. EG.
Chip 1(Left side of the screen) CSA(1)=0 CSB(2)=0
Chip 2(Middle of the screen) CSA(1)=1 CSB(2)=0
Chip 3(RIght side of the screen) CSA(1)=0 CSB(2)=1

I have also seen these CHIP Select addressed as
Chip 1(Left side of the screen) CSA(1)=1 CSB(2)=0
Chip 2(Middle of the screen) CSA(1)=0 CSB(2)=1

The screen in the link you provided doesn't seem to have CS pins, but it does have an RS(Register Select Pin) I suspect if you address 0, thats chip 1, and 1 for chip 2, but i would read the user manual of your specific display to be sure
